### ISSUE TITLE
Add Liked Videos to be tracked

### ISSUE THREAD

**Issue by Trickster29** [ninsky/recovermyvideotracker#11]
I use "liked videos" to store songs that i like cause its super easy just to press like vs moving to playlist. 

id like if this could be tracked aswell, i do not mind setting "liked videos" to public

if this is already a feature please tell me how cause i don't see a way to override the automatic selection of playlists

**Comment by ninsky** [comment]
Hello Trickster

Thanks for this request. This feature should be possible and I've flagged this with a "medium" priority label on my backlog.

I've also removed "while Liked Videos are not private" of the title of this request as this would make difference if the videos are public or private.

BR
Nino

**Comment by ninsky** [comment]
Hello @Trickster29 

I've just released the feature to monitor the YouTube "Liked videos" playlist. It should take max. 1 week till the "Liked videos" playlist should appear in your playlist list on RecoverMy.Video. The YouTube sync is about once a week.

The YouTube sync default of the "Liked videos" is disabled. So in order to activate the sync please push the blue toggle.

![image](https://user-images.githubusercontent.com/1623045/115569877-eafe8700-a2bd-11eb-8ed6-f770e0e33f57.png)


You will notice a "?" sign at the amout of video badge of your "Liked videos" playlist. The reason is that YouTube doesn't deliver the amount of videos on this playlist. Strange but true. This is also the reason that I don't consider those videos regarding the limit of currently 20.000 videos which you can monitor.  

Feedback welcome!

Enjoy :)
Nino

PS: I will close this issue after some time. Let's wait if there will be some feedback.
