### ISSUE TITLE
[Suggestion] Can we only track specific playlists?

### ISSUE THREAD

**Issue by Invisible40** [ninsky/recovermyvideotracker#18]
**Is your feature request related to a problem? Please describe.**
Unfortunately, I checked into my account, and I saw I had reached the 8,000 video max. I didn't even know this was a thing until now.

**Describe the solution you'd like**
I mainly use the service to track three playlists. Two of them are music, and the other is just favorite videos. For instance, I have two playlists in particular that combine to 3,000 videos. I don't have any use tracking these playlists. 

Since my 8,000 video limit is mainly concerned with three playlists, I would like a solution that only tracks specific playlists, which will go well below the maximum number. 

**Describe alternatives you've considered**
I haven't considered alternatives. I may look for other services if they provide something similar, but I've been using Recovermy.videos for well over a year and love the service.

**Comment by ninsky** [comment]
Hello Invisible40

This feature requests [already exists](https://github.com/ninsky/recovermyvideotracker/issues/6) within this backlog. Indeed, this would be a great addition. I still have it on my todo list but I'm still working on some other tasks with a higher priority. So I think this will take some months for sure.

I'm closing this issue because it's a duplicate.

BR
Nino
