### ISSUE TITLE
Google Play to YouTube Music import caused about 1000 lost videos

### ISSUE THREAD

**Issue by probablykasper** [ninsky/recovermyvideotracker#23]
Google is offering a tool to import Google Play Music music to YouTube Music due to GPM shutting down. All my songs from these playlists now show up as "Lost" in RecoverMy.Video. All of them are mp3s that I manually uploaded (not videos), and they're not actually lost.

It's not the biggest problem in the world, but there could be a reasonable fix for it.

Support article about the import tool: https://support.google.com/youtubemusic/answer/9698084?hl=en

**Comment by ninsky** [comment]
Hello Kaspar

I've heard about the move to YouTube Music. I liked Google Play Music... but you know how it goes... from time to time Google shuts down services ;)

I've also tried to import my manually imported music to YouTube Music via Google's export/import tool. But it just managed to transfer my paid albums (not my mp3s witch I've uploaded manually, strange).

I could imagine that YouTube Music stores such mp3s on YouTube playlists and therefore these mp3s seem to appear via the YouTube API on RecoverMy.Video. I assume that YouTube wasn't able to identify the titles of such manually uploaded mp3s and for this reason I could imagine that those videos are handled like "private" vidoes which are considered as "lost" videos by RecoverMy.Video if a real title of such a mp3 was never published via YouTube API.

I haven't test it yet but for now I would close this issue as I think, that this issue is not fixable. Maybe I will give it another try. I'm also planning a feature to flush your list of "lost" videos on RecoverMy.Video if it gets to long.

Anyway, thanks for your report! I appreciate that!

BR
Nino

**Comment by probablykasper** [comment]
@ninsky Since it's limited to showing 200 in the Lost tab, I don't really know if I'll ever see actual lost videos unless I take a few hours to manually delete the thousand(s?) of songs.

If I could delete everything from a specific playlist, that would be a great solution

**Comment by ninsky** [comment]
@

**Comment by ninsky** [comment]
@probablykasper you can use the export tool on recovermy.video to export all of your lost videos including links to archive.org and Google

**Comment by probablykasper** [comment]
@ninsky Ah, that's helpful! Looks like it's 1017 lost videos

**Comment by ninsky** [comment]
Okay, hope this helps. Closing this issue.
