### ISSUE TITLE
Cant view recovered videos

### ISSUE THREAD

**Issue by dudebub91** [ninsky/recovermyvideotracker#25]
Hi,

first I want to say that I love your website and that it saved a handful of songs in my playlists, so thanks for that. Unfortunately I cant seem to acess them anymore. I got a mail that says I got 14 recovered songs that redirects me to the homepage. When I check the box and press "Recover now" it just starts the registration process again. When I type my email it says this email is already taken. What do I do now?

**Comment by ninsky** [comment]
Hard to say what's happening. Would take some time to debug your issue. The good new is, that I'm working on a major release which will give you better error messages in case of such an issue. I think it will be fixed. I will inform all users via email as soon as I push the major release to production. Hope it's okay when I'm closing this issue as it doesn't make sense right now to dig into it because of the new release coming soon.
