### ISSUE TITLE
Obsolete password requirements

### ISSUE THREAD

**Issue by outfrost** [ninsky/recovermyvideotracker#29]
**Describe the bug**
When creating a new account, the website presents the user with a set of password composition requirements.

![Screenshot from 2020-11-25 19-35-29](https://user-images.githubusercontent.com/18421230/100271662-20df4f80-2f5a-11eb-9e3c-c957f2268343.png)

All of these requirements, except the length of course, have been proven across the industry to not increase security enough to be worth the burden they impose on the user, be it via having to remember, write down, or generate a password that complies with all of the requirements at once.

In fact, it can be argued they reduce security.

Let's say the user does not use a password manager, and opts instead to remember their passwords. They're not allowed to use a complex but memorable password, such as a 4-word made-up phrase, because it won't pass the requirements. They therefore reuse the one 8-character password they've used everywhere, or a slight variation on it, such as appending the first letter of the website's name to the end. It's reasonable to guess it contains a `,` or `.`, since these characters are least likely to be rejected by a website with restrictive password requirements.

Needless to say, that password will not only probably end up in a hacked passwords dump from another website, it likely has already been in one. The complexity is also often illusory (see `pA55w+rd`).

Now, if the user does use a password manager, the composition requirements just add friction for no measurable benefit. In some cases, they may slightly decrease the effective entropy of the generated password, because some facts about it can be taken for granted, while the character set used to generate it likely already contains lower- and uppercase letters, digits, and various special characters. In any case, any generated password of reasonable length (16+ characters), without special characters, already exceeds the entropy of a user-provided password, even one with all the requirements fulfilled.

For example, I cannot directly use a password Firefox generated for me:

![Screenshot from 2020-11-25 20-02-47](https://user-images.githubusercontent.com/18421230/100272859-1de55e80-2f5c-11eb-830d-2e44e81874d8.png)

For more information, I'd recommend having a look at an [article about NIST’s new password rules](https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/), which outlines some good and bad practices around password-based authentication.

**Expected behavior**
I would find it reasonable to increase the minimum password length to 12 or 16, and ditch password composition requirements, instead focusing on disallowing passwords commonly found in dumps, facilitating use of complex and memorable passphrases, as well as generated passwords with and without unusual Unicode characters.

RecoverMy.Video does however seem to already handle long and complex generated passwords well, so that's good :)

**Desktop**
 - OS: Manjaro 20.2
 - Firefox 83.0

**Additional context**
I don't mean to come across as petty, but given that some password requirements are already in place, I assume that password security is of importance, so I decided to chime in and discuss how it can be improved.

**Comment by ninsky** [comment]
Hello outfrost

Thanks a lot for your input. I really appreciate your advice how to strengthen security and ease of use of RecoverMy.Video!

After reading your post I think I've got your point. The reason why I've implemented such password requirements is that I've validated some random passwords by using [Have I Been Pwned](https://haveibeenpwned.com/Passwords). Nearly all of these passwords are in this database. Even the creative or random ones! 

So I came to the conclusion that it's better to have those implemented password requirements instead of disappointing users trying to use complicated passwords which seem to be safe. It's very annoying if you enter an "illusory" complicated or safe password and RecoverMy.Video's "have I been pwned" validation would tell you that it's not. Even if it's true.

As this is the fist implementation of a password requirement on RecoverMy.Video I've decided to initially raise the bar and get some user feedback (e.g. conversion rate of the registration form). It's easier to lower the bar afterwards as the other way round.

But as said, I see your point... the NIST article is very interesting and I think I will reconsider my decision in the near future. There are some additions like an invisible login captcha, throttling etc. which I will also take into consideration.

Any suggestions are welcome :)

Best
Nino

**Comment by outfrost** [comment]
I can see where you're coming from. It's certainly difficult to gauge what kinds of passwords are safe _enough_ to use.

While checking haveibeenpwned is generally a good idea (at least for the individual), I think it's impossible to completely avoid reuse of _someone else's_ complex password that has already been leaked. As more and more people use randomly generated passwords, hash collisions might also become a slight problem.

I would always advocate for using longer passwords, if one can think of or generate one, though your approach is probably valid too. I appreciate that you are taking this seriously :)

**Comment by ninsky** [comment]
@outfrost , I've adjusted the password requirements to a minimum lenght of 12 chars and 1 letter and a "have i been pwned" check. 

On my analytics I could see that many users have struggeled with those complex requirements. You were right that this could lead to even more unsecure passwords.

Thanks again for your precious issue you've raised on november 2020. 

BR
Nino

**Comment by outfrost** [comment]
Thank you for resolving it! I'm glad I could provide useful feedback :)
