### ISSUE TITLE
When I try to login to my account a message that says "Username could not be found" pops up.

### ISSUE THREAD

**Issue by ac4man** [ninsky/recovermyvideotracker#34]
**Describe the bug**
When I try to login into my account I get the message "Username could not be found." I am positive that I am putting in the right login information, and I am positive that I have an account because I still get emails about recovered videos from 
noreply@recovermy.video.

**To Reproduce**
1. Type in email 
2. Type in Password
3. Hit sign in
4. A message pops up at the top of the screen saying "Username could not be found"

**Expected behavior**
I expected to be able to login into my account.

**Screenshots**
https://i.imgur.com/M8HhIhY.png

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Comment by ninsky** [comment]
Hello ac4man

I suppose you didn't get or notice my mail from november. I've informed all users that I have to close all user accounts because of a major update of RecoverMy.Video. This sounds stupid but it was the only way to bring this update to production within a short matter of time.

Please register a new account.

Thanks for your understanding
Nino
