### ISSUE TITLE
Don't add videos that were removed by the user

### ISSUE THREAD

**Issue by JXWw3wLD9LArcR7c** [ninsky/recovermyvideotracker#5]
**Is your feature request related to a problem? Please describe.**
I see that videos that I removed personally also appear on the list. Makes me think they were deleted when they weren't (I don't take in mind what videos I remove and what I don't)

**Describe the solution you'd like**
Don't show videos that were removed by the user, only show videos that were made deleted, privated, copyrighted, unlisted, blocked, or etc on youtube

**Describe alternatives you've considered**
None

**Additional context**
I can't imagine a good way to achieve this, maybe you can't fix it, or maybe you can find a way to fix it. At least I don't remove that many songs

**Comment by ninsky** [comment]
Hi SimonGhoul

I'm aware of this issue. Unfortunately I can't distinguish between a video removed by yourself or by YouTube. The only thing I could do is to add a "remove from list" button so that you can remove such videos on RecoverMy.Video's recovered list by yourself.

BR
Nino

**Comment by hashimaziz1** [comment]
I noticed this today, and it's a real shame there's no way to distinguish the two, as for someone who is constantly removing videos from playlists (because I had finished watching them, for example), it makes the entire service useless for me, which is annoying because I was just getting my hopes up for how well you've built it. 

The manually remove user-removed videos would be an option, but only if it comes with a bulk remove mode (i.e using checkboxes and Delete All Selected buttons), as it would otherwise be impossible for me to scour through all removed videos. Currently I have about 700 detected removed videos, and I estimate *at least* 80% were removed by myself.

**Comment by ninsky** [comment]
Hello Kaos-Industries

The bulk delete capability is a good idea. I will take account of it when implementing the "remove video from list" feature.

BR
Nino

**Comment by hashimaziz1** [comment]
I'm glad to hear it. Do you know of a possible ETA for this feature?

**Comment by ninsky** [comment]
@Kaos-Industries this is fixed! Videos removed by a user aren't considered as recovered any more.

**Comment by hashimaziz1** [comment]
> 
> 
> @Kaos-Industries this is fixed! Videos removed by a user aren't considered as recovered any more.

Excellent! You're a legend, thanks for the invaluable work you do on this web app.
